Factor API key checking into a separate command
Following suggestion from @rose at https://discuss.circleci.com/t/new-orb-leanpub/29833/6?u=zzamboni

diff --git a/src/@orb.yml b/src/@orb.yml
--- a/src/@orb.yml
+++ b/src/@orb.yml
@@ -80,14 +80,14 @@ jobs:
         default: false
     executor: leanpub-executor
     steps:
+      - check-env-var-param:
+          param: <<parameters.api-key>>
+          error-message: >
+            ERROR: You need to provide your Leanpub API key in environment variable <<parameters.api-key>>.
       - checkout
       - run:
           name: Publish book
           command: |
-            if [[ -z "${<<parameters.api-key>>}" ]]; then
-              echo "ERROR: You need to provide your Leanpub API key in environment variable <<parameters.api-key>>."
-              exit 1
-            fi
             export ECHO_CMD=<<#parameters.dry-run>>echo<</parameters.dry-run>>
             export RELEASE_NOTES=<<# parameters.auto-release-notes>>$([[ -n "$CIRCLE_TAG" ]] && git cat-file -p `git rev-parse $CIRCLE_TAG` | sed '1,/^$/d')<</ parameters.auto-release-notes>>
             if [[ -n "$RELEASE_NOTES" ]]; then
@@ -97,6 +97,23 @@ jobs:
             fi
 
 commands:
+
+  check-env-var-param:
+    description: Check that an env-var parameter is defined
+    parameters:
+      param:
+        description: Parameter to check
+        type: env_var_name
+      error-message:
+        description: Message to print if parameter is undefined
+        type: string
+        default: "ERROR: You need to set environment variable <<parameter.param>>"
+    steps:
+      - run: |
+          if [[ -z "${<<parameters.param>>}" ]]; then
+            echo "<<parameters.error-message>>"
+            exit 1
+          fi
 
   # Generic entry point for triggering a Leanpub API call
   api-call:
@@ -115,13 +132,13 @@ commands:
         type: boolean
         default: false
     steps:
+      - check-env-var-param:
+          param: <<parameters.api-key>>
+          error-message: >
+            ERROR: You need to provide your Leanpub API key in environment variable <<parameters.api-key>>.
       - run:
           name: Call Leanpub API /<<parameters.endpoint>>.json
           command: |
-            if [[ -z "${<<parameters.api-key>>}" ]]; then
-              echo "ERROR: You need to provide your Leanpub API key in environment variable <<parameters.api-key>>."
-              exit 1
-            fi
             <<#parameters.dry-run>>echo <</parameters.dry-run>>curl -d "api_key=${<<parameters.api-key>>}" <<parameters.extra-params>> https://leanpub.com/<<parameters.book-slug>>/<<parameters.endpoint>>.json
 
   trigger-subset-preview:
